[tools]
node = "22.18.0"

[tasks.build]
description = "Build the nuxt application"
run = "pnpm run build"

[tasks.dev]
description = "Run the dev application"
run = "pnpm run dev"

[tasks.typecheck]
description = "Run the typechecker"
run = "pnpm dlx nuxt typecheck"

[tasks.linter]
description = "Run the linter"
run = "pnpm exec eslint --ext .js,.ts,.vue . --fix"

[tasks.act_validate]
description = "Run the github action validate locally"
run = ""

[tasks.act_deploy]
description = "Run the github action deploy locally"
run = ""

[tasks.act_preview]
description = "Run the github action preview locally"
run = ""

[tasks.act_clear_preview]
description = "Run the github action clear_preview locally"
run = ""